# .pre-commit-config.yaml
default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1024']
        exclude: ^web/|^web/node_modules/
      - id: check-toml
        exclude: ^web/
      - id: check-yaml
        args: ["--unsafe"]
        exclude: ^web/
      - id: end-of-file-fixer
        exclude: ^web/
      # - id: trailing-whitespace
      - id: check-json
        exclude: ^web/
      - id: debug-statements
        exclude: ^web/
      - id: check-case-conflict
        exclude: ^web/
      - id: detect-private-key
        exclude: ^web/
      - id: name-tests-test
        args:
          - "--pytest-test-first"
        exclude: ^web/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: ^web/
      - id: ruff-format
        exclude: ^web/

  - repo: https://github.com/codespell-project/codespell.git
    rev: v2.4.1
    hooks:
      - id: codespell
        files: \.(py)$
        exclude: ^web/

  - repo: https://github.com/hukkin/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        files: ^(?!CHANGELOG\.md$).*\.(md|markdown)$
        exclude: ^web/
        additional_dependencies:
          - mdformat-gfm
          - mdformat-black

  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
        exclude: ^web/
